[build]
  command = "npm run build"
  publish = ".svelte-kit/output/client"

[build.environment]
  NODE_VERSION = "20.19.0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"